### ISSUE TITLE
Exception on Logging into app

### ISSUE THREAD

**Issue by markmova** [ResearchStack/SampleApp#10]
Hi,

I clone SampleApp and build it using gradle 2.10.
Build was successful and I saw the first page of app as below:

![sample app](https://cloud.githubusercontent.com/assets/21079371/17959272/91d8b54c-6ab4-11e6-9a80-190f061e8de3.png)

But when I click on any button bellow exception raise:

```
08-25 06:14:08.793 4171-4171/org.researchstack.sampleapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: org.researchstack.sampleapp, PID: 4171
                                                                           java.lang.IllegalArgumentException: Expected receiver of type org.researchstack.skin.ui.OnboardingActivity, but got android.support.v7.widget.TintContextWrapper
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at android.view.View$DeclaredOnClickListener.onClick(View.java:4447)
                                                                               at android.view.View.performClick(View.java:5198)
                                                                               at android.view.View$PerformClick.run(View.java:21147)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I use Android Studio 2.1.1 and sdk 23.0.2

Thanks.

**Comment by nrlakin** [comment]
@markmova, did you modify the following line in app/build.gradle (the app-level gradle build file) before building?

`compile 'com.android.support:appcompat-v7:23.2.1'`

Android Studio often prompts you to update to the latest version of this library (7.24.something), but this breaks compatibility with other dependencies and causes the issue you're seeing. Verify that you're using the correct version of this library and let me know if the issue persists.

**Comment by markmova** [comment]
@nrlakin,
You right, Android Studio updates appcompat lib to v7:23.3.0.
I change it to v7:23.2.1 and now it works fine.

Thanks
